#
#Wed Apr 01 08:55:01 PET 2026
goog\:chromeOptions={args\=[--start-maximized, --incognito, --guest, --disable-notifications, --disable-popup-blocking, --disable-save-password-bubble, --disable-features\=PasswordCheck,PasswordManagerOnboarding,AutofillServerCommunication, remote-allow-origins\=*], extensions\=[], prefs\={profile.default_content_setting_values.notifications\=2, credentials_enable_service\=false, autofill.credit_card_enabled\=false, autofill.profile_enabled\=false, profile.password_manager_enabled\=false, profile.password_manager_leak_detection\=false}}
acceptInsecureCerts=false
browserName=chrome
